Update node-sass
$ docker-compose run --rm --no-deps app npm install
...
> node-sass@3.13.1 postinstall /app/node_modules/node-sass
> node scripts/build.js
...
  g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_
WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-
D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILD
ING_NODE_EXTENSION' -I/root/.node-gyp/12.16.1/include/node -I/root/.node-gyp/12.16.1/src -I/root/.nod
e-gyp/12.16.1/deps/openssl/config -I/root/.node-gyp/12.16.1/deps/openssl/openssl/include -I/root/.nod
e-gyp/12.16.1/deps/uv/include -I/root/.node-gyp/12.16.1/deps/zlib -I/root/.node-gyp/12.16.1/deps/v8/i
nclude -I../../nan -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64
-O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.dep
s/Release/obj.target/binding/src/create_string.o.d.raw   -c -o Release/obj.target/binding/src/create_
string.o ../src/create_string.cpp
In file included from ../src/create_string.cpp:1:
...
../src/create_string.cpp: In function 'char* create_string(Nan::MaybeLocal<v8::Value>)':
../src/create_string.cpp:17:37: error: no matching function for call to 'v8::String::Utf8Value::Utf8V
alue(v8::Local<v8::Value>&)'
   17 |   v8::String::Utf8Value string(value);
      |                                     ^
...