Upgrade to gulp 4.x
$ docker-compose up
fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (/app/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/app/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/app/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/app/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/app/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:3:10)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/app/node_modules/vinyl-fs/lib/src/getContents/index.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/app/node_modules/vinyl-fs/lib/src/index.js:8:19)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/app/node_modules/vinyl-fs/index.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/app/node_modules/gulp/index.js:7:11)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/app/gulp-tasks/file_manager.coffee:1:21)
    at Object.<anonymous> (/app/gulp-tasks/file_manager.coffee:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.loadFile (/app/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
    at Module.load (/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/app/gulp-tasks/common.coffee:1:21)
    at Object.<anonymous> (/app/gulp-tasks/common.coffee:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.loadFile (/app/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
    at Module.load (/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/app/gulpfile.coffee:1:1)
    at Object.<anonymous> (/app/gulpfile.coffee:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.loadFile (/app/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
    at Module.load (/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/app/gulpfile.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Liftoff.handleArguments (/app/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.execute (/app/node_modules/liftoff/index.js:203:12)
    at module.exports (/app/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/app/node_modules/liftoff/index.js:195:5)
    at /app/node_modules/liftoff/index.js:165:9
    at /app/node_modules/v8flags/index.js:93:14
    at FSReqCallback.oncomplete (fs.js:154:23)